blog/urls.py
from django.urls import path
from .views import index

app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
]

config/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from home.views import index
from company.views import about, contact
from authentication.views import login_view, logout_view
from accounts.views import register

urlpatterns = [
    path('', index, name='index'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('login', login_view, name='login'),
    path('register', register, name='register'),
    path('logout', logout_view, name='logout'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import TimeStampModel


class Post(TimeStampModel):
    pass

company/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models


class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

home/models.py
from django.db import models
from core.enums import PublishStatusEnum
from core.models import TimeStampModel


class FrontCarousel(TimeStampModel):
    title = models.CharField(max_length=50)
    student_type = models.CharField(
        max_length=10, choices=PublishStatusEnum.choices())

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Username",
                "id": "username"
            }
        )
    )

    first_name = forms.CharField(
        label='First Name',
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "First Name",
                "id": "firstName"
            }
        )
    )

    last_name = forms.CharField(
        label='Last Name',
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Last Name",
                "id": "lastName"
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Your email",
                "id": "email"
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "password"
            }
        )
    )

    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "password2"
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password2 != password:
            raise forms.ValidationError("Passwords must match.")
        return data

authentication/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Username",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control mb-3"
            }
        )
    )

company/forms.py
from django import forms


class ContactForm(forms.Form):
    fullname = forms.CharField(
        label="Full Name",
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Your full name"
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Your email demo@example.com"
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Content",
                "rows": "4",
            }
        )
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import RegisterForm


def register(request):
    form = RegisterForm(request.POST or None)
    context = {
        "form": form,
    }
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = User.objects.create_user(username, email, password)
        if user is not None:
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            return redirect('/login')
        else:
            form = RegisterForm()

    return render(request, 'register.html', context)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm


def login_view(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form,
        "alert": "none"
    }
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            form = LoginForm()
            context["alert"] = "block"

    return render(request, 'login.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

blog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'blog/index.html', {})

company/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm


def about(request):
    return render(request, 'about.html', {})


def contact(request):
    form = ContactForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        print(form.cleaned_data)
        print(form.cleaned_data.get('fullname'))
        print(form.cleaned_data.get('email'))
        print(form.cleaned_data.get('content'))
        form = ContactForm()
        return redirect('/contact')
    # if request.method == 'POST':
    #     print(request.POST)
    #     print(request.POST.get('fullname'))
    #     print(request.POST.get('email'))
    #     print(request.POST.get('content'))
    return render(request, 'contact.html', context)

core/views.py
from django.shortcuts import render

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {})

accounts/templates/register.html
{% extends "base.html" %}

{% block head_title %}
Register
{% endblock head_title %}

{% block main_contents %}
<div class="container">
    <div class="py-3 text-center">
        <h2>User Register Form</h2>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <form method="POST"> {% csrf_token %}

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">{{ form.first_name.label}}</label>
                        {{ form.first_name}}
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">{{ form.last_name.label }}</label>
                        {{ form.last_name}}
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="username">{{ form.username.label }}</label>
                        {{ form.username }}
                        <div class="invalid-feedback">
                            Please enter your shipping address.
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="email">{{ form.email.label }}</label>
                        {{ form.email }}
                        <div class="invalid-feedback">
                            Please enter your shipping address.
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="password">{{ form.password.label }}</label>
                        {{ form.password }}
                        <div class="invalid-feedback">
                            Please enter your shipping address.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password2">{{ form.password2.label }}</label>
                        {{ form.password2 }}
                        <div class="invalid-feedback">
                            Please enter your shipping address.
                        </div>
                    </div>

                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Register</button>
            </form>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock main_contents %}

authentication/templates/login.html
{% extends "base.html" %}

{% block head_title %}
Login
{% endblock head_title %}

{% block main_contents %}
<div class="container">
    <div class="py-5 text-center">
        <h2>Login Here</h2>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form method="POST"> {% csrf_token %}
                {{ form }}
                <div class="alert alert-warning form-control d-{{ alert }}" role="alert">
                    User is not found!
                </div>
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock main_contents %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block head_title %}
Blog Home
{% endblock head_title %}

{% block main_contents %}
<h1>Blog Index</h1>
{% endblock main_contents %}

company/templates/about.html
{% extends "base.html" %}

{% block head_title %}
- About Us
{% endblock head_title %}

{% block main_contents %}
<h1>About Us</h1>
{% endblock main_contents %}

company/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}
- Contact Us
{% endblock head_title %}

{% block local_css %}
<link rel="stylesheet" href="{% static 'css/maps/location.css' %}">
{% endblock local_css %}

{% block main_contents %}
<div class="container">
    <div class="py-3 text-center">
        <h2>Contact Us</h2>
    </div>

    <div class="row">
        <div class="col-md-7">
            <h4 class="mb-3">Contact Form</h4>
            <form method="POST"> {% csrf_token %}
                {{ form }}
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
            </form>
        </div>
        <div class="col-md-5 mb-4">

            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Find Us in Map</span>
            </h4>
            <div id="map"></div>

            <div class="row my-3 pl-3">
                <div class="d-flex mr-2">
                    <i class="fas fa-map-marker-alt p-1 mr-3 align-self-top"></i>
                    <p>
                        123 Jane Mount Street <br>
                        Haleyfurt, Arizona 79971
                    </p>
                </div>
                <div class="d-flex">
                    <i class="fas fa-phone p-1 mr-3 align-self-top"></i>
                    <p>(019)067-8503</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main_contents %}

{% block local_js %}
<script src="{% static 'js/maps/location.js' %}"></script>
{% endblock local_js %}

home/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}
Welcome
{% endblock head_title %}

{% block main_contents %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="4"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="5"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="6"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="7"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="8"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="9"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'wallpapers/001.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/002.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/003.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/004.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Fourth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/005.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Fifth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/006.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Sixth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/007.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Seventh slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/008.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Eighth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/009.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Nineth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'wallpapers/010.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Tenth slide label</h5>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock main_contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Django Blog - {% block head_title %}{% endblock head_title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "base/css.html" %}

    {% block local_css %}
    {% endblock local_css %}

</head>

<body>
    {% include "base/navbar.html" %}

    {% block main_contents %}
    {% endblock main_contents %}

    {% include "base/js.html" %}

    {% block local_js %}
    {% endblock local_js %}
</body>

</html>

templates/base/css.html
{% load static %}

<link rel="icon" href="{% static 'icons/favicon.png' %}" type="image/png">

<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/site.css' %}">

templates/base/js.html
{% load key_tags %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={% get_google_map_api_key %}&callback=initMap"></script>

templates/base/navbar.html
{% load datetime_tags %}
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Blogs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Company</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
                    <a class="dropdown-item" href="{% url 'contact' %}">Contact Us</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav mr-auto my-2 my-md-0 mr-md-3">
            <li class="nav-item active">
                {% if user.is_authenticated %}
                <a class="nav-link disabled" href="#">Good {% time_of_day %} {{ user.first_name }}</a>
                {% endif %}
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="myaccount" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                    <img src="{% static 'icons/users/me.png' %}" width="30" height="30" class="rounded-circle">
                    {% else %}
                    <img src="{% static 'icons/user.png' %}" width="30" height="30" class="rounded-circle">
                    {% endif %}

                </a>
                <div class="dropdown-menu" aria-labelledby="myaccount">
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Change Password</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/test.html
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <a class="navbar-brand" href="#">
        <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/logo_white.png"
            width="30" height="30" alt="logo">
        BootstrapBay
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg"
                        width="40" height="40" class="rounded-circle">
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Dashboard</a>
                    <a class="dropdown-item" href="#">Edit Profile</a>
                    <a class="dropdown-item" href="#">Log Out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>